

.PHONY: clean

all:
	make -f Makefile_2.0.mk

install:
	make -f Makefile_2.0.mk install

1.42:
	make -f Makefile_1.42.mk

2.0:
	make -f Makefile_2.0.mk

install-1.42:
	make -f Makefile_1.42.mk install

install-2.0:
	make -f Makefile_2.0.mk install

clean:
	make -f Makefile_1.42.mk clean
	make -f Makefile_2.0.mk clean

