//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureTestDriver.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint MobileProxiesCount {
            get {
                return ((uint)(this["MobileProxiesCount"]));
            }
            set {
                this["MobileProxiesCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://inflo-bsm-dev.azurewebsites.net/api/bsm")]
        public string MobileBsmWebApi {
            get {
                return ((string)(this["MobileBsmWebApi"]));
            }
            set {
                this["MobileBsmWebApi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public uint MobileBsmBundleMaxSize {
            get {
                return ((uint)(this["MobileBsmBundleMaxSize"]));
            }
            set {
                this["MobileBsmBundleMaxSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6500")]
        public uint MobileBsmBundlerTimeout {
            get {
                return ((uint)(this["MobileBsmBundlerTimeout"]));
            }
            set {
                this["MobileBsmBundlerTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public uint MobileBsmGenerateInterval {
            get {
                return ((uint)(this["MobileBsmGenerateInterval"]));
            }
            set {
                this["MobileBsmGenerateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public uint MobileBsmMaxSendWorkerCount {
            get {
                return ((uint)(this["MobileBsmMaxSendWorkerCount"]));
            }
            set {
                this["MobileBsmMaxSendWorkerCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/webapi/i2v")]
        public string MobileI2VWebApi {
            get {
                return ((string)(this["MobileI2VWebApi"]));
            }
            set {
                this["MobileI2VWebApi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public uint MobileI2VPollInterval {
            get {
                return ((uint)(this["MobileI2VPollInterval"]));
            }
            set {
                this["MobileI2VPollInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\milky-way\\projects\\NSD\\INFLO\\Team Collaboration\\msgs")]
        public string BSMBerFileLocation {
            get {
                return ((string)(this["BSMBerFileLocation"]));
            }
            set {
                this["BSMBerFileLocation"] = value;
            }
        }
    }
}
