// <auto-generated />
namespace PAI.FRATIS.SFL.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Driver_IsDeleted_Archivable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Driver_IsDeleted_Archivable));
        
        string IMigrationMetadata.Id
        {
            get { return "201409081432343_Driver_IsDeleted_Archivable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
