// <auto-generated />
namespace PAI.FRATIS.SFL.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Miami_Add_JobShipperConsignee_and_LocationOptions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Miami_Add_JobShipperConsignee_and_LocationOptions));
        
        string IMigrationMetadata.Id
        {
            get { return "201408192052330_Miami_Add_JobShipperConsignee_and_LocationOptions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
