// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;

using IDTO.Common.Models;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace IDTO.iPhone
{
	public partial class FavoritesViewController : IDTOViewController
	{
		public event FavoriteSelectedDelegate FavoriteSelected;

		public FavoritesViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			FavoritesTableSource tableSource = new FavoritesTableSource ();

			tableSource.FavoriteSelected += (String name) => {
				if(this.FavoriteSelected!=null)
				{
					this.FavoriteSelected(name);
				}
			};

			tableView.Source = tableSource;


			setupConnectorView ();
		}

		private void setupConnectorView ()
		{
			this.AddConnectorView (lblFavorites);
			ExtendToView = tableView;
		}
			
		partial void editClicked (NSObject sender)
		{
			tableView.Editing = true;
		}
	}
}
