// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

using IDTO.Common.Models;
using GoogleAnalytics.iOS;

namespace IDTO.iPhone
{
	public partial class SearchResultsTableViewController : IDTOViewController
	{
		public TripSearchResult SearchResults { get; set; }

		public Itinerary mSelectedItinerary;

		public SearchResultsTableViewController (IntPtr handle) : base (handle)
		{
		}
			
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			SearchResultsTableSource tableSource = new SearchResultsTableSource (SearchResults);

			tableSource.ItinerarySelected += (Itinerary itinerary) => {
				mSelectedItinerary = itinerary;

				this.PerformSegue("PlanTripDetailsSegue", this);
			};

			tableView.Source = tableSource;

			setupConnectorView ();
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);

			if (segue.Identifier == "PlanTripDetailsSegue") {
				GAI.SharedInstance.DefaultTracker.Send (GAIDictionaryBuilder.CreateEvent("ui_action", "trip details", "trip details", null).Build());
				TripDetailsViewController vc = (TripDetailsViewController)segue.DestinationViewController;
				vc.ItineraryToShow = mSelectedItinerary;
				vc.Criteria = SearchResults.searchCriteria;

			}
		}

		private void setupConnectorView ()
		{
			this.AddConnectorView (lblSearchResults);
			ExtendToView = tableView;
		}


	}
}
