//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INCZONE.Model
{
    using System;
    using System.Collections.Generic;

    public partial class AlarmLevel : Interfaces.IEntity
    {
        public AlarmLevel()
        {
            this.AudibleVisualAlarms = new HashSet<AudibleVisualAlarm>();
            this.VehicleAlarms = new HashSet<VehicleAlarm>();
        }
    
        public int Id { get; set; }
        public int Level { get; set; }
    
        public virtual ICollection<AudibleVisualAlarm> AudibleVisualAlarms { get; set; }
        public virtual ICollection<VehicleAlarm> VehicleAlarms { get; set; }
    }
}
