//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INCZONE.Model
{
    using System;
    using System.Collections.Generic;

    public partial class CapWINConfiguration : Interfaces.IEntity
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string HostURL { get; set; }
        public string ComPort { get; set; }
        public string BaudRate { get; set; }
        public int DistanceToIncident { get; set; }
        public int LaneData { get; set; }
    }
}
