//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INCZONE.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IncZoneEntities : DbContext
    {
        public IncZoneEntities()
            : base("name=IncZoneEntities")
        {
        }

        public IncZoneEntities(string justDatabaseConnString)
            : base(justDatabaseConnString)
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlarmConfiguration> AlarmConfigurations { get; set; }
        public virtual DbSet<AlarmLevel> AlarmLevels { get; set; }
        public virtual DbSet<AudibleVisualAlarm> AudibleVisualAlarms { get; set; }
        public virtual DbSet<CapWINConfiguration> CapWINConfigurations { get; set; }
        public virtual DbSet<DGPSConfiguration> DGPSConfigurations { get; set; }
        public virtual DbSet<DSRCConfiguration> DSRCConfigurations { get; set; }
        public virtual DbSet<EventLog> EventLogs { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<LogLevel> LogLevels { get; set; }
        public virtual DbSet<MapLink> MapLinks { get; set; }
        public virtual DbSet<MapNode> MapNodes { get; set; }
        public virtual DbSet<MapSet> MapSets { get; set; }
        public virtual DbSet<VehicleAlarm> VehicleAlarms { get; set; }
        public virtual DbSet<BluetoothConfig> BluetoothConfigs { get; set; }
    }
}
