//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INCZONE.Model
{
    using System;
    using System.Collections.Generic;

    public partial class MapLink : Interfaces.IEntity
    {
        public int Id { get; set; }
        public int startId { get; set; }
        public int endId { get; set; }
    
        public virtual MapNode MapNode { get; set; }
        public virtual MapNode MapNode1 { get; set; }
    }
}
