//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INCZONE.Model
{
    using System;
    using System.Collections.Generic;

    public partial class MapNode : Interfaces.IEntity
    {
        public MapNode()
        {
            this.MapLinks = new HashSet<MapLink>();
            this.MapLinks1 = new HashSet<MapLink>();
        }
    
        public int Id { get; set; }
        public double lat { get; set; }
        public double @long { get; set; }
        public double elevation { get; set; }
        public int laneWidth { get; set; }
        public int directionality { get; set; }
        public int xOffset { get; set; }
        public int yOffset { get; set; }
        public int zOffset { get; set; }
        public int positionalAccuracyP1 { get; set; }
        public int positionalAccuracyP2 { get; set; }
        public int positionalAccuracyP3 { get; set; }
        public int laneOrder { get; set; }
        public int postedSpeed { get; set; }
        public int mapSetId { get; set; }
        public double distance { get; set; }
        public System.Guid GuId { get; set; }
        public System.Guid mapSetGuId { get; set; }
    
        public virtual ICollection<MapLink> MapLinks { get; set; }
        public virtual ICollection<MapLink> MapLinks1 { get; set; }
        public virtual MapSet MapSet { get; set; }
    }
}
