//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INCZONE.Model
{
    using System;
    using System.Collections.Generic;

    public partial class MapSet : Interfaces.IEntity
    {
        public MapSet()
        {
            this.MapNodes = new HashSet<MapNode>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.Guid GuId { get; set; }
    
        public virtual ICollection<MapNode> MapNodes { get; set; }
    }
}
