//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon.InfloDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration_RoadwayLinks
    {
        public string RoadwayId { get; set; }
        public string LinkId { get; set; }
        public double BeginMM { get; set; }
        public double EndMM { get; set; }
        public string StartCrossStreetName { get; set; }
        public string EndCrossStreetName { get; set; }
        public string UpstreamLinkId { get; set; }
        public string DownstreamLinkId { get; set; }
        public Nullable<short> NumberLanes { get; set; }
        public Nullable<short> SpeedLimit { get; set; }
        public Nullable<short> NumberDetectorStations { get; set; }
        public string DetectorStations { get; set; }
        public string ESS { get; set; }
        public string VSLSignId { get; set; }
        public string DMSId { get; set; }
        public string RSEId { get; set; }
        public string Direction { get; set; }
    }
}
