//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon.InfloDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration_ESS
    {
        public string ESSId { get; set; }
        public string ESSType { get; set; }
        public string ESSOperationType { get; set; }
        public string ESSMobilityType { get; set; }
        public Nullable<double> BeginMM { get; set; }
        public Nullable<double> EndMM { get; set; }
    }
}
