//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon.InfloDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TME_CVData_Input
    {
        public long CVMessageIdentifier { get; set; }
        public string NomadicDeviceID { get; set; }
        public Nullable<System.DateTime> DateGenerated { get; set; }
        public Nullable<double> Speed { get; set; }
        public Nullable<short> Heading { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public double MMLocation { get; set; }
        public Nullable<bool> CVQueuedState { get; set; }
        public Nullable<double> CoefficientOfFriction { get; set; }
        public Nullable<short> Temperature { get; set; }
        public string RoadwayId { get; set; }
        public Nullable<double> LateralAcceleration { get; set; }
        public Nullable<double> LongitudinalAcceleration { get; set; }
    }
}
