//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon.InfloDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TME_TSSESS_Link
    {
        public string RoadwayId { get; set; }
        public string LinkId { get; set; }
        public System.DateTime DateProcessed { get; set; }
        public Nullable<short> IntervalLength { get; set; }
        public double TSSSpeed { get; set; }
        public Nullable<double> ESSSpeed { get; set; }
        public short TSSVolume { get; set; }
        public Nullable<double> TSSOccupancy { get; set; }
        public Nullable<bool> Congested { get; set; }
        public Nullable<bool> Queued { get; set; }
        public Nullable<short> RecommendedSpeed { get; set; }
        public string RecommendedSpeedSource { get; set; }
        public string CurrentDMSMessage { get; set; }
        public Nullable<short> CurrentVSLSignSpeed { get; set; }
    }
}
