//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon.InfloDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TME_ESSData_Input
    {
        public string ESSId { get; set; }
        public Nullable<double> ESSVisibilityDistance { get; set; }
        public string ESSVisibilityStatus { get; set; }
        public Nullable<double> ESSCoefficientOfFriction { get; set; }
        public string ESSSurfaceStatus { get; set; }
        public System.DateTime DateReceived { get; set; }
    }
}
