//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon.InfloDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TME_ESSMobileData_Input
    {
        public string MobileESSId { get; set; }
        public Nullable<double> Latitude { get; set; }
        public double Longitude { get; set; }
        public Nullable<double> Bearing { get; set; }
        public Nullable<double> Friction { get; set; }
        public string ObservationPavement { get; set; }
    }
}
