//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon.InfloDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMEOutput_QWARN_QueueInfo
    {
        public System.DateTime DateGenerated { get; set; }
        public short BOQ_MMLocation { get; set; }
        public string BOQ_LinkId { get; set; }
        public double FOQ_MMLocation { get; set; }
        public string FOQ_LinkId { get; set; }
        public double RateOfQueueGrowth { get; set; }
        public short SPeed_In_Queue { get; set; }
    }
}
