//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon.InfloDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMEOutput_QWARNMessage_CV
    {
        public System.DateTime DateGenerated { get; set; }
        public string RoadwayID { get; set; }
        public double BOQMMLocation { get; set; }
        public double FOQMMLocation { get; set; }
        public Nullable<short> SpeedInQueue { get; set; }
        public Nullable<double> RateOfQueueGrowth { get; set; }
        public Nullable<int> ValidityDuration { get; set; }
    }
}
