//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon.InfloDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMEOutput_WRTM_Alerts
    {
        public System.DateTime DateGenerated { get; set; }
        public string WeatherAlert { get; set; }
        public string Justification { get; set; }
        public string RoadwayId { get; set; }
        public double BeginMM { get; set; }
        public double EndMM { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    }
}
