//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon.InfloDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMEOutput_ShockWaveInformation
    {
        public System.DateTime Timestamp { get; set; }
        public string RoadwayIdentifier { get; set; }
        public double MileMarkerLocation { get; set; }
        public short SchockwaveSpeed { get; set; }
        public string SchockwaveDirection { get; set; }
    }
}
