//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfloCommon.InfloDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMEOutput_SPDHARMMessage_Infrastructure
    {
        public System.DateTime DateGenerated { get; set; }
        public short RecommendedSpeed { get; set; }
        public string VSLId { get; set; }
        public string Justification { get; set; }
        public string LinkId { get; set; }
    }
}
